name: Spellcheck
on:
  pull_request:
    paths:
    - '**.js'
    - '**.txt'
    - '**.html'
    - '**.md'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Spelling
      uses: rojopolis/spellcheck-github-actions@v0.5.0
    with:
      config_path: config/.spellcheck.yml
      
name: Lint
on:
  pull_request:
    paths:
    - '**.md'
jobs:
    markdownlint-cli:
        runs-on: ubuntu-latest
        steps:
        - uses: nosborn/github-action-markdown-cli@v1.1.1
          with:
            files: .
